### PR TITLE
MRG: Cleaner and faster

### PR DESCRIPTION
**Pull request by larsoner**
This has various fixes and speed enhancements (~40 sec to ~1 sec) to @hsonntag's changes.

### CODE REVIEW

**Comment by larsoner** [comment]
@bmaess your latest commit broke my PR :(

Is now a good time for me to rebase?

**Comment by bmaess** [comment]
@Eric89GXL - sorry, I still was working on this time scale issue. The variable name midpt made me think that this describes the mid of the interval. In the meanwhile, I think that this does not matter and we could use it as the left side of the interval. That would simplify the code a bit. I think, that currently the MF output and the cHPI output are comparable in most ways ... including the time axis.

Functions for testing are added as well, but my last merge broke @hsonntag test routine. I don't understand why 
The test data suite now contains some new files needed for my test functions. They are at the server in my rep.

**Comment by bmaess** [comment]
what does rebase mean? Ignoring @hsonntag tests - I would close the case from my side here

**Comment by larsoner** [comment]
> The test data suite now contains some new files needed for my test functions. They are at the server in my rep.

Go ahead and open a PR into the `mne-testing-data` repository and we'll go from there.

I'll work on fixing my PR to fix @hsonntag's test routines

**Comment by larsoner** [comment]
Okay, rebase complete. You should be able to merge this one. The tests pass other than the ones that require new test data

**Comment by larsoner** [comment]
> what does rebase mean?

It means 1) rolling back the commit history (sets of changes) of my branch until a common starting point is found with the new base (your branch), 2) applying the commits of the new base that aren't present in my branch, and then 3) applying the commits from my branch that aren't in the new branch. It rewrites history of my commits to make it look like I made my changes on top of (after) yours, even though originally I did them concurrently or before.

**Pull request merged**
